version: '3.8'

services:
  app:
    build: .
    command: /start-app.sh
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - docker.app.env
      - docker.db.env
    volumes:
      - .storage/logs:/var/www/application/logs
      - .storage/backup:/var/www/backup
      - .storage/updates:/var/www/updates
      - .storage/uploads:/var/www/uploads

  web:
    build: .
    command: /start-web.sh
    restart: unless-stopped
    depends_on:
      - app
    env_file:
      - docker.app.env
    volumes:
      - .storage/logs:/var/www/application/logs
      - .storage/backup:/var/www/backup
      - .storage/updates:/var/www/updates
      - .storage/uploads:/var/www/uploads
    ports:
      - 8089:80

  cron:
    build: .
    command: /start-cron.sh
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - docker.app.env
      - docker.db.env
    volumes:
      - .storage/logs:/var/www/application/logs
      - .storage/backup:/var/www/backup
      - .storage/updates:/var/www/updates
      - .storage/uploads:/var/www/uploads

  mariadb:
    restart: unless-stopped
    image: mariadb:10.10
    env_file: docker.db.env
    volumes:
      - .mariadb:/var/lib/mysql
